name: flutter_agora_helper
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  agora_rtc_engine: ^5.3.0
  agora_rtm: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
